#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
from unittest.mock import MagicMock

sys.modules["rdkit"] = MagicMock()
sys.modules["rdkit.Numerics"] = MagicMock()
sys.modules["rdkit.DistanceGeometry"] = MagicMock()
sys.modules["rdkit.ML"] = MagicMock()
sys.modules["rdkit.ML.Descriptors"] = MagicMock()
sys.modules["rdkit.ML.Composite"] = MagicMock()
sys.modules["rdkit.ML.DecTree"] = MagicMock()
sys.modules["rdkit.ML.ModelPackage"] = MagicMock()
sys.modules["rdkit.ML.Neural"] = MagicMock()
sys.modules["rdkit.ML.InfoTheory"] = MagicMock()
sys.modules["rdkit.ML.Scoring"] = MagicMock()
sys.modules["rdkit.ML.KNN"] = MagicMock()
sys.modules["rdkit.ML.SLT"] = MagicMock()
sys.modules["rdkit.ML.MLUtils"] = MagicMock()
sys.modules["rdkit.ML.Cluster"] = MagicMock()
sys.modules["rdkit.ML.Data"] = MagicMock()
sys.modules["rdkit.ML.NaiveBayes"] = MagicMock()
sys.modules["rdkit.Chem"] = MagicMock()
sys.modules["rdkit.Chem.SimpleEnum"] = MagicMock()
sys.modules["rdkit.Chem.Pharm2D"] = MagicMock()
sys.modules["rdkit.Chem.Fingerprints"] = MagicMock()
sys.modules["rdkit.Chem.FeatMaps"] = MagicMock()
sys.modules["rdkit.Chem.MolKey"] = MagicMock()
sys.modules["rdkit.Chem.MolStandardize"] = MagicMock()
sys.modules["rdkit.Chem.Draw"] = MagicMock()
sys.modules["rdkit.Chem.ChemUtils"] = MagicMock()
sys.modules["rdkit.Chem.Suppliers"] = MagicMock()
sys.modules["rdkit.Chem.AtomPairs"] = MagicMock()
sys.modules["rdkit.Chem.Subshape"] = MagicMock()
sys.modules["rdkit.Chem.MolDb"] = MagicMock()
sys.modules["rdkit.Chem.fmcs"] = MagicMock()
sys.modules["rdkit.Chem.Features"] = MagicMock()
sys.modules["rdkit.Chem.EState"] = MagicMock()
sys.modules["rdkit.Chem.Pharm3D"] = MagicMock()
sys.modules["rdkit.Chem.Scaffolds"] = MagicMock()
sys.modules["rdkit.Chem.Fraggle"] = MagicMock()
sys.modules["rdkit.ForceField"] = MagicMock()
sys.modules["rdkit.DataStructs"] = MagicMock()
sys.modules["rdkit.VLib"] = MagicMock()
sys.modules["rdkit.VLib.NodeLib"] = MagicMock()
sys.modules["rdkit.SimDivFilters"] = MagicMock()
sys.modules["rdkit.Dbase"] = MagicMock()
sys.modules["rdkit.Avalon"] = MagicMock()
sys.modules["rdkit.DataManip"] = MagicMock()
sys.modules["rdkit.DataManip.Metric"] = MagicMock()
sys.modules["rdkit.Geometry"] = MagicMock()
sys.modules["rdkit.utils"] = MagicMock()
