before_script:
  - pip install --user tox flake8

stages:
  - static-analysis
  - unit-test
  - coverage-analysis

Python2.7:
  stage: unit-test
  script:
    - tox -e py27

Python3.7:
  stage: unit-test
  script:
    - tox -e py37

Coverage:
  stage: coverage-analysis
  script:
    - tox -e coverage
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'

Lint:
  stage: static-analysis
  script:
    - flake8 --max-line-length=80 graphdot/
