before_script:
  - pip install --user tox flake8
  - export PATH=/usr/local/cuda/bin:$PATH
  - export LD_LIBRARY_PATH=/usr/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH

stages:
  - static-analysis
  - unit-test
  - coverage-analysis

Python2.7:
  stage: unit-test
  script:
    - tox -e py27

Python3.7:
  stage: unit-test
  script:
    - tox -e py37

Coverage:
  stage: coverage-analysis
  script:
    - tox -e coverage
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'

Lint:
  stage: static-analysis
  script:
    - flake8 --max-line-length=80 graphdot/
    - flake8 --max-line-length=80
      --ignore=E121,E123,E126,E226,E24,E704,F401,W503,W504
      test/
