before_script:
  - pip install --user tox flake8 pandas
  - export PATH=/usr/local/cuda/bin:$PATH
  - export LD_LIBRARY_PATH=/usr/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH

stages:
  - static-analysis
  - unit-test
  - coverage-analysis
  - benchmark

Lint:
  stage: static-analysis
  script:
    - make lint

Python3.5:
  stage: unit-test
  script:
    - tox -e py35

Python3.6:
  stage: unit-test
  script:
    - tox -e py36

Python3.7:
  stage: unit-test
  script:
    - tox -e py37

Coverage:
  stage: coverage-analysis
  script:
    - tox -e coverage
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+\%)$/'

Benchmark:
  stage: benchmark
  script:
    - tox -e benchmark

Docs:
  stage: static-analysis
  script:
    - tox -e docs
