version: 2
sphinx:
  configuration: docs/conf.py
formats: all
python:
  version: 3.7
  install:
    - requirements: requirements/common.txt
    - requirements: requirements/docs.txt
    - method: pip
